baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'OKLM'
theme = 'typo'

[params]
description = "OKLM website"

# Appearance settings
theme = 'auto'
colorPalette = 'default'
hideHeader = false

# Intro on main page, content is markdown
homeIntroContent = """
## Hello
Glad to see you on [OKLM]()

I host several services, [the list is here](services).

For more information about privacy, visit [this page](privacy).
"""

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'

# Breadcrumbs
breadcrumbs = false


# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "services"
url = "/services"

[[params.menu]]
name = "privacy"
url = "/privacy"

[[params.menu]]
name = "contact"
url = "/contact"

[[params.menu]]
name = "about"
url = "/about"

# Syntax highligth on code blocks
[markup]
[markup.highlight]
style = 'algol'
[markup.goldmark.renderer]
unsafe= true

# Giscus comments
[params.giscus]
enable = false
repo = "user/repo"
repoid = "repoId"
category = "General"
categoryid = "categoryId"
mapping = "pathname"
theme = "preferred_color_scheme"
